version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      # install dependencies in frontend
      - run:
          name: install frontend dependencies
          command: |
            npm frontend:install
      # install dependencies in backend
      - run:
          name: install backend dependencies
          command: |
            npm backend:install
      # build frontend
      - run:
          name: build frontend
          command: |
            npm frontend:build
      # build backend
      - run:
          name: build backend
          command: |
            npm backend:build
